// Generated by CoffeeScript 1.12.6
var Website, config, fs, i, len, ref, site, w, websites, yaml;

fs = require('fs');

Website = require('./index.js');

yaml = require('yamljs');

config = yaml.load("config.yml");

websites = [];

ref = config.websites;
for (i = 0, len = ref.length; i < len; i++) {
  w = ref[i];
  site = new Website(w);
  websites.push(site);
  console.log("Starting loop for: " + w.name);
  site.mainLoop(config.globalConfig.desiredRegex, function(url, data) {
    var name;
    name = (new RegExp(w.filename.exp)).match(url)[w.filename.index];
    fs.writeFileSync("found/" + name + ".txt", data);
    return console.log("[" + w.name + "] Found relevant data in paste: " + url + " | Saved to found/" + name + ".txt");
  });
}
